export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_ERROR = "ORDER_PAY_ERROR";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const MARK_ORDER_PAID_REQUEST = "MARK_ORDER_PAID_REQUEST";
export const MARK_ORDER_PAID_SUCCESS = "MARK_ORDER_PAID_SUCCESS";
export const MARK_ORDER_PAID_ERROR = "MARK_ORDER_PAID_ERROR";

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_ERROR = "GET_MY_ORDERS_ERROR";
export const GET_MY_ORDERS_RESET = "GET_MY_ORDERS_RESET";
