export const PAYMENT_ORDER_CREATE_REQUEST = "PAYMENT_ORDER_CREATE_REQUEST";
export const PAYMENT_ORDER_CREATE_SUCCESS = "PAYMENT_ORDER_CREATE_SUCCESS";
export const PAYMENT_ORDER_CREATE_ERROR = "PAYMENT_ORDER_CREATE_ERROR";
export const PAYMENT_ORDER_CREATE_RESET = "PAYMENT_ORDER_CREATE_RESET";

export const PAYMENT_VERIFY_REQUEST = "PAYMENT_VERIFY_REQUEST";
export const PAYMENT_VERIFY_SUCCESS = "PAYMENT_VERIFY_SUCCESS";
export const PAYMENT_VERIFY_ERROR = "PAYMENT_VERIFY_ERROR";
